engines:
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.sh"
  - "**.css"
  - "**.js"
  - "src/*"
  - "src/**/*"
  - "test/*"
  - "test/**/*"
  - "stories/*"
  - "stories/**/*"
  - "scripts/*"
