engines:
  fixme:
    enabled: true
  stylelint:
    enabled: true
ratings:
  paths:
    - '**/*.sh'
    - '**/*.js'
    - 'src/*'
    - 'src/**/*'
    - 'test/*'
    - 'test/**/*'
    - 'stories/*'
    - 'stories/**/*'
    - 'scripts/*'
exclude_patterns:
  - '**/node_modules/'
  - '**/__screenshots__/'
  - '**/__snapshots__/'
  - 'storybook/stories/'
  - 'flow-typed/'
  - '**/*.spec.js'
  - 'test/env.js'
