// flow-typed signature: 4cfa4f7582ea9033172c1ff36539e6a2
// flow-typed version: <<STUB>>/babel-plugin-macros_v2.4.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-macros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-macros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-macros/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-macros/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/index'>;
}
