// flow-typed signature: 42382df6491eac2d53548bf2787d4d16
// flow-typed version: <<STUB>>/bithound_v1.7.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bithound'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bithound' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bithound/bithound' {
  declare module.exports: any
}

declare module 'bithound/commands/check' {
  declare module.exports: any
}

declare module 'bithound/commands/token' {
  declare module.exports: any
}

declare module 'bithound/tests/unit/check' {
  declare module.exports: any
}

declare module 'bithound/tests/unit/token' {
  declare module.exports: any
}

// Filename aliases
declare module 'bithound/bithound.js' {
  declare module.exports: $Exports<'bithound/bithound'>
}
declare module 'bithound/commands/check.js' {
  declare module.exports: $Exports<'bithound/commands/check'>
}
declare module 'bithound/commands/token.js' {
  declare module.exports: $Exports<'bithound/commands/token'>
}
declare module 'bithound/tests/unit/check.js' {
  declare module.exports: $Exports<'bithound/tests/unit/check'>
}
declare module 'bithound/tests/unit/token.js' {
  declare module.exports: $Exports<'bithound/tests/unit/token'>
}
