// flow-typed signature: 634abd9e15feba9e53752a9c245c3584
// flow-typed version: <<STUB>>/codeclimate-test-reporter_v0.5.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codeclimate-test-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codeclimate-test-reporter' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codeclimate-test-reporter/bin/codeclimate' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/ci_info' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/formatter' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/git_info' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/gocover_parse' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/http_client' {
  declare module.exports: any
}

declare module 'codeclimate-test-reporter/test/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'codeclimate-test-reporter/bin/codeclimate.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/bin/codeclimate'>
}
declare module 'codeclimate-test-reporter/ci_info.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/ci_info'>
}
declare module 'codeclimate-test-reporter/formatter.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/formatter'>
}
declare module 'codeclimate-test-reporter/git_info.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/git_info'>
}
declare module 'codeclimate-test-reporter/gocover_parse.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/gocover_parse'>
}
declare module 'codeclimate-test-reporter/http_client.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/http_client'>
}
declare module 'codeclimate-test-reporter/test/test.js' {
  declare module.exports: $Exports<'codeclimate-test-reporter/test/test'>
}
