// flow-typed signature: 58b480cafb3a983bf188b3d3ee536532
// flow-typed version: <<STUB>>/condition-circle_v1.5.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'condition-circle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'condition-circle' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'condition-circle/src/condition-circle' {
  declare module.exports: any
}

// Filename aliases
declare module 'condition-circle/src/condition-circle.js' {
  declare module.exports: $Exports<'condition-circle/src/condition-circle'>
}
