// flow-typed signature: c86b49193ec12b08b29d52ce58fe4918
// flow-typed version: <<STUB>>/condition-circle_v2.0.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'condition-circle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'condition-circle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'condition-circle/src/condition-circle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'condition-circle/src/condition-circle.js' {
  declare module.exports: $Exports<'condition-circle/src/condition-circle'>;
}
