// flow-typed signature: 06b31e587c0cea92fbe065832d157477
// flow-typed version: <<STUB>>/cxs_vhttps://github.com/arahansen/cxs#d593d14e708c4f5c17cb2105cb9435ae87ade362/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cxs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cxs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cxs/benchmarks/index' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/cxs' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/emotion' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/fela' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/glamorous' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/inline-styles' {
  declare module.exports: any;
}

declare module 'cxs/benchmarks/lib/styled-components' {
  declare module.exports: any;
}

declare module 'cxs/component' {
  declare module.exports: any;
}

declare module 'cxs/dist/component' {
  declare module.exports: any;
}

declare module 'cxs/dist/createTheme' {
  declare module.exports: any;
}

declare module 'cxs/dist/index' {
  declare module.exports: any;
}

declare module 'cxs/dist/monocomponent' {
  declare module.exports: any;
}

declare module 'cxs/dist/monolithic' {
  declare module.exports: any;
}

declare module 'cxs/dist/ThemeProvider' {
  declare module.exports: any;
}

declare module 'cxs/docs/About' {
  declare module.exports: any;
}

declare module 'cxs/docs/App' {
  declare module.exports: any;
}

declare module 'cxs/docs/Badge' {
  declare module.exports: any;
}

declare module 'cxs/docs/Banner' {
  declare module.exports: any;
}

declare module 'cxs/docs/Bar' {
  declare module.exports: any;
}

declare module 'cxs/docs/Box' {
  declare module.exports: any;
}

declare module 'cxs/docs/build' {
  declare module.exports: any;
}

declare module 'cxs/docs/bundle' {
  declare module.exports: any;
}

declare module 'cxs/docs/Button' {
  declare module.exports: any;
}

declare module 'cxs/docs/Card' {
  declare module.exports: any;
}

declare module 'cxs/docs/colors' {
  declare module.exports: any;
}

declare module 'cxs/docs/Column' {
  declare module.exports: any;
}

declare module 'cxs/docs/Container' {
  declare module.exports: any;
}

declare module 'cxs/docs/CTA' {
  declare module.exports: any;
}

declare module 'cxs/docs/entry' {
  declare module.exports: any;
}

declare module 'cxs/docs/Flex' {
  declare module.exports: any;
}

declare module 'cxs/docs/Footer' {
  declare module.exports: any;
}

declare module 'cxs/docs/Header' {
  declare module.exports: any;
}

declare module 'cxs/docs/Heading' {
  declare module.exports: any;
}

declare module 'cxs/docs/HideMobile' {
  declare module.exports: any;
}

declare module 'cxs/docs/Link' {
  declare module.exports: any;
}

declare module 'cxs/docs/Logo' {
  declare module.exports: any;
}

declare module 'cxs/docs/media' {
  declare module.exports: any;
}

declare module 'cxs/docs/meta' {
  declare module.exports: any;
}

declare module 'cxs/docs/Pre' {
  declare module.exports: any;
}

declare module 'cxs/docs/Stats' {
  declare module.exports: any;
}

declare module 'cxs/docs/Text' {
  declare module.exports: any;
}

declare module 'cxs/docs/theme' {
  declare module.exports: any;
}

declare module 'cxs/docs/Title' {
  declare module.exports: any;
}

declare module 'cxs/docs/Tweet' {
  declare module.exports: any;
}

declare module 'cxs/docs/Usage' {
  declare module.exports: any;
}

declare module 'cxs/monolithic' {
  declare module.exports: any;
}

declare module 'cxs/src/component' {
  declare module.exports: any;
}

declare module 'cxs/src/createTheme' {
  declare module.exports: any;
}

declare module 'cxs/src/index' {
  declare module.exports: any;
}

declare module 'cxs/src/monocomponent' {
  declare module.exports: any;
}

declare module 'cxs/src/monolithic' {
  declare module.exports: any;
}

declare module 'cxs/src/ThemeProvider' {
  declare module.exports: any;
}

declare module 'cxs/test/browser' {
  declare module.exports: any;
}

declare module 'cxs/test/component' {
  declare module.exports: any;
}

declare module 'cxs/test/createTheme' {
  declare module.exports: any;
}

declare module 'cxs/test/cxs' {
  declare module.exports: any;
}

declare module 'cxs/test/monolithic' {
  declare module.exports: any;
}

declare module 'cxs/ThemeProvider' {
  declare module.exports: any;
}

declare module 'cxs/webpack.config' {
  declare module.exports: any;
}

declare module 'cxs/x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cxs/benchmarks/index.js' {
  declare module.exports: $Exports<'cxs/benchmarks/index'>;
}
declare module 'cxs/benchmarks/lib/cxs.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/cxs'>;
}
declare module 'cxs/benchmarks/lib/emotion.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/emotion'>;
}
declare module 'cxs/benchmarks/lib/fela.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/fela'>;
}
declare module 'cxs/benchmarks/lib/glamorous.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/glamorous'>;
}
declare module 'cxs/benchmarks/lib/inline-styles.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/inline-styles'>;
}
declare module 'cxs/benchmarks/lib/styled-components.js' {
  declare module.exports: $Exports<'cxs/benchmarks/lib/styled-components'>;
}
declare module 'cxs/component.js' {
  declare module.exports: $Exports<'cxs/component'>;
}
declare module 'cxs/dist/component.js' {
  declare module.exports: $Exports<'cxs/dist/component'>;
}
declare module 'cxs/dist/createTheme.js' {
  declare module.exports: $Exports<'cxs/dist/createTheme'>;
}
declare module 'cxs/dist/index.js' {
  declare module.exports: $Exports<'cxs/dist/index'>;
}
declare module 'cxs/dist/monocomponent.js' {
  declare module.exports: $Exports<'cxs/dist/monocomponent'>;
}
declare module 'cxs/dist/monolithic.js' {
  declare module.exports: $Exports<'cxs/dist/monolithic'>;
}
declare module 'cxs/dist/ThemeProvider.js' {
  declare module.exports: $Exports<'cxs/dist/ThemeProvider'>;
}
declare module 'cxs/docs/About.js' {
  declare module.exports: $Exports<'cxs/docs/About'>;
}
declare module 'cxs/docs/App.js' {
  declare module.exports: $Exports<'cxs/docs/App'>;
}
declare module 'cxs/docs/Badge.js' {
  declare module.exports: $Exports<'cxs/docs/Badge'>;
}
declare module 'cxs/docs/Banner.js' {
  declare module.exports: $Exports<'cxs/docs/Banner'>;
}
declare module 'cxs/docs/Bar.js' {
  declare module.exports: $Exports<'cxs/docs/Bar'>;
}
declare module 'cxs/docs/Box.js' {
  declare module.exports: $Exports<'cxs/docs/Box'>;
}
declare module 'cxs/docs/build.js' {
  declare module.exports: $Exports<'cxs/docs/build'>;
}
declare module 'cxs/docs/bundle.js' {
  declare module.exports: $Exports<'cxs/docs/bundle'>;
}
declare module 'cxs/docs/Button.js' {
  declare module.exports: $Exports<'cxs/docs/Button'>;
}
declare module 'cxs/docs/Card.js' {
  declare module.exports: $Exports<'cxs/docs/Card'>;
}
declare module 'cxs/docs/colors.js' {
  declare module.exports: $Exports<'cxs/docs/colors'>;
}
declare module 'cxs/docs/Column.js' {
  declare module.exports: $Exports<'cxs/docs/Column'>;
}
declare module 'cxs/docs/Container.js' {
  declare module.exports: $Exports<'cxs/docs/Container'>;
}
declare module 'cxs/docs/CTA.js' {
  declare module.exports: $Exports<'cxs/docs/CTA'>;
}
declare module 'cxs/docs/entry.js' {
  declare module.exports: $Exports<'cxs/docs/entry'>;
}
declare module 'cxs/docs/Flex.js' {
  declare module.exports: $Exports<'cxs/docs/Flex'>;
}
declare module 'cxs/docs/Footer.js' {
  declare module.exports: $Exports<'cxs/docs/Footer'>;
}
declare module 'cxs/docs/Header.js' {
  declare module.exports: $Exports<'cxs/docs/Header'>;
}
declare module 'cxs/docs/Heading.js' {
  declare module.exports: $Exports<'cxs/docs/Heading'>;
}
declare module 'cxs/docs/HideMobile.js' {
  declare module.exports: $Exports<'cxs/docs/HideMobile'>;
}
declare module 'cxs/docs/Link.js' {
  declare module.exports: $Exports<'cxs/docs/Link'>;
}
declare module 'cxs/docs/Logo.js' {
  declare module.exports: $Exports<'cxs/docs/Logo'>;
}
declare module 'cxs/docs/media.js' {
  declare module.exports: $Exports<'cxs/docs/media'>;
}
declare module 'cxs/docs/meta.js' {
  declare module.exports: $Exports<'cxs/docs/meta'>;
}
declare module 'cxs/docs/Pre.js' {
  declare module.exports: $Exports<'cxs/docs/Pre'>;
}
declare module 'cxs/docs/Stats.js' {
  declare module.exports: $Exports<'cxs/docs/Stats'>;
}
declare module 'cxs/docs/Text.js' {
  declare module.exports: $Exports<'cxs/docs/Text'>;
}
declare module 'cxs/docs/theme.js' {
  declare module.exports: $Exports<'cxs/docs/theme'>;
}
declare module 'cxs/docs/Title.js' {
  declare module.exports: $Exports<'cxs/docs/Title'>;
}
declare module 'cxs/docs/Tweet.js' {
  declare module.exports: $Exports<'cxs/docs/Tweet'>;
}
declare module 'cxs/docs/Usage.js' {
  declare module.exports: $Exports<'cxs/docs/Usage'>;
}
declare module 'cxs/monolithic.js' {
  declare module.exports: $Exports<'cxs/monolithic'>;
}
declare module 'cxs/src/component.js' {
  declare module.exports: $Exports<'cxs/src/component'>;
}
declare module 'cxs/src/createTheme.js' {
  declare module.exports: $Exports<'cxs/src/createTheme'>;
}
declare module 'cxs/src/index.js' {
  declare module.exports: $Exports<'cxs/src/index'>;
}
declare module 'cxs/src/monocomponent.js' {
  declare module.exports: $Exports<'cxs/src/monocomponent'>;
}
declare module 'cxs/src/monolithic.js' {
  declare module.exports: $Exports<'cxs/src/monolithic'>;
}
declare module 'cxs/src/ThemeProvider.js' {
  declare module.exports: $Exports<'cxs/src/ThemeProvider'>;
}
declare module 'cxs/test/browser.js' {
  declare module.exports: $Exports<'cxs/test/browser'>;
}
declare module 'cxs/test/component.js' {
  declare module.exports: $Exports<'cxs/test/component'>;
}
declare module 'cxs/test/createTheme.js' {
  declare module.exports: $Exports<'cxs/test/createTheme'>;
}
declare module 'cxs/test/cxs.js' {
  declare module.exports: $Exports<'cxs/test/cxs'>;
}
declare module 'cxs/test/monolithic.js' {
  declare module.exports: $Exports<'cxs/test/monolithic'>;
}
declare module 'cxs/ThemeProvider.js' {
  declare module.exports: $Exports<'cxs/ThemeProvider'>;
}
declare module 'cxs/webpack.config.js' {
  declare module.exports: $Exports<'cxs/webpack.config'>;
}
declare module 'cxs/x.js' {
  declare module.exports: $Exports<'cxs/x'>;
}
