// flow-typed signature: 36ba28de5bb52b95f9b1fb3abcb1f597
// flow-typed version: <<STUB>>/picturebook_v2.0.0-beta.18/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'picturebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'picturebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'picturebook/dist/browser' {
  declare module.exports: any;
}

declare module 'picturebook/dist/defaults' {
  declare module.exports: any;
}

declare module 'picturebook/dist/getFiles' {
  declare module.exports: any;
}

declare module 'picturebook/dist/getFiles.spec' {
  declare module.exports: any;
}

declare module 'picturebook/dist/index' {
  declare module.exports: any;
}

declare module 'picturebook/dist/loadStories' {
  declare module.exports: any;
}

declare module 'picturebook/dist/loadStories.spec' {
  declare module.exports: any;
}

declare module 'picturebook/dist/nightwatchConfig' {
  declare module.exports: any;
}

declare module 'picturebook/dist/picturebook.types' {
  declare module.exports: any;
}

declare module 'picturebook/dist/picturebook.web' {
  declare module.exports: any;
}

declare module 'picturebook/dist/runTests' {
  declare module.exports: any;
}

declare module 'picturebook/dist/screenshot/tests/picturebook' {
  declare module.exports: any;
}

declare module 'picturebook/dist/screenshot/tests/teardown' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/browser' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/compareImages' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/folderStructure' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/folderStructure.spec' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/getParents' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/image' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/index' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/logs' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/moduleAsFunction' {
  declare module.exports: any;
}

declare module 'picturebook/dist/utils/moduleAsFunction.spec' {
  declare module.exports: any;
}

declare module 'picturebook/src/browser' {
  declare module.exports: any;
}

declare module 'picturebook/src/defaults' {
  declare module.exports: any;
}

declare module 'picturebook/src/getFiles' {
  declare module.exports: any;
}

declare module 'picturebook/src/getFiles.spec' {
  declare module.exports: any;
}

declare module 'picturebook/src/index' {
  declare module.exports: any;
}

declare module 'picturebook/src/loadStories' {
  declare module.exports: any;
}

declare module 'picturebook/src/loadStories.spec' {
  declare module.exports: any;
}

declare module 'picturebook/src/nightwatchConfig' {
  declare module.exports: any;
}

declare module 'picturebook/src/picturebook.types' {
  declare module.exports: any;
}

declare module 'picturebook/src/runTests' {
  declare module.exports: any;
}

declare module 'picturebook/src/screenshot/tests/picturebook' {
  declare module.exports: any;
}

declare module 'picturebook/src/screenshot/tests/teardown' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/browser' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/compareImages' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/folderStructure' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/folderStructure.spec' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/getParents' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/image' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/index' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/logs' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/moduleAsFunction' {
  declare module.exports: any;
}

declare module 'picturebook/src/utils/moduleAsFunction.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'picturebook/dist/browser.js' {
  declare module.exports: $Exports<'picturebook/dist/browser'>;
}
declare module 'picturebook/dist/defaults.js' {
  declare module.exports: $Exports<'picturebook/dist/defaults'>;
}
declare module 'picturebook/dist/getFiles.js' {
  declare module.exports: $Exports<'picturebook/dist/getFiles'>;
}
declare module 'picturebook/dist/getFiles.spec.js' {
  declare module.exports: $Exports<'picturebook/dist/getFiles.spec'>;
}
declare module 'picturebook/dist/index.js' {
  declare module.exports: $Exports<'picturebook/dist/index'>;
}
declare module 'picturebook/dist/loadStories.js' {
  declare module.exports: $Exports<'picturebook/dist/loadStories'>;
}
declare module 'picturebook/dist/loadStories.spec.js' {
  declare module.exports: $Exports<'picturebook/dist/loadStories.spec'>;
}
declare module 'picturebook/dist/nightwatchConfig.js' {
  declare module.exports: $Exports<'picturebook/dist/nightwatchConfig'>;
}
declare module 'picturebook/dist/picturebook.types.js' {
  declare module.exports: $Exports<'picturebook/dist/picturebook.types'>;
}
declare module 'picturebook/dist/picturebook.web.js' {
  declare module.exports: $Exports<'picturebook/dist/picturebook.web'>;
}
declare module 'picturebook/dist/runTests.js' {
  declare module.exports: $Exports<'picturebook/dist/runTests'>;
}
declare module 'picturebook/dist/screenshot/tests/picturebook.js' {
  declare module.exports: $Exports<'picturebook/dist/screenshot/tests/picturebook'>;
}
declare module 'picturebook/dist/screenshot/tests/teardown.js' {
  declare module.exports: $Exports<'picturebook/dist/screenshot/tests/teardown'>;
}
declare module 'picturebook/dist/utils/browser.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/browser'>;
}
declare module 'picturebook/dist/utils/compareImages.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/compareImages'>;
}
declare module 'picturebook/dist/utils/folderStructure.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/folderStructure'>;
}
declare module 'picturebook/dist/utils/folderStructure.spec.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/folderStructure.spec'>;
}
declare module 'picturebook/dist/utils/getParents.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/getParents'>;
}
declare module 'picturebook/dist/utils/image.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/image'>;
}
declare module 'picturebook/dist/utils/index.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/index'>;
}
declare module 'picturebook/dist/utils/logs.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/logs'>;
}
declare module 'picturebook/dist/utils/moduleAsFunction.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/moduleAsFunction'>;
}
declare module 'picturebook/dist/utils/moduleAsFunction.spec.js' {
  declare module.exports: $Exports<'picturebook/dist/utils/moduleAsFunction.spec'>;
}
declare module 'picturebook/src/browser.js' {
  declare module.exports: $Exports<'picturebook/src/browser'>;
}
declare module 'picturebook/src/defaults.js' {
  declare module.exports: $Exports<'picturebook/src/defaults'>;
}
declare module 'picturebook/src/getFiles.js' {
  declare module.exports: $Exports<'picturebook/src/getFiles'>;
}
declare module 'picturebook/src/getFiles.spec.js' {
  declare module.exports: $Exports<'picturebook/src/getFiles.spec'>;
}
declare module 'picturebook/src/index.js' {
  declare module.exports: $Exports<'picturebook/src/index'>;
}
declare module 'picturebook/src/loadStories.js' {
  declare module.exports: $Exports<'picturebook/src/loadStories'>;
}
declare module 'picturebook/src/loadStories.spec.js' {
  declare module.exports: $Exports<'picturebook/src/loadStories.spec'>;
}
declare module 'picturebook/src/nightwatchConfig.js' {
  declare module.exports: $Exports<'picturebook/src/nightwatchConfig'>;
}
declare module 'picturebook/src/picturebook.types.js' {
  declare module.exports: $Exports<'picturebook/src/picturebook.types'>;
}
declare module 'picturebook/src/runTests.js' {
  declare module.exports: $Exports<'picturebook/src/runTests'>;
}
declare module 'picturebook/src/screenshot/tests/picturebook.js' {
  declare module.exports: $Exports<'picturebook/src/screenshot/tests/picturebook'>;
}
declare module 'picturebook/src/screenshot/tests/teardown.js' {
  declare module.exports: $Exports<'picturebook/src/screenshot/tests/teardown'>;
}
declare module 'picturebook/src/utils/browser.js' {
  declare module.exports: $Exports<'picturebook/src/utils/browser'>;
}
declare module 'picturebook/src/utils/compareImages.js' {
  declare module.exports: $Exports<'picturebook/src/utils/compareImages'>;
}
declare module 'picturebook/src/utils/folderStructure.js' {
  declare module.exports: $Exports<'picturebook/src/utils/folderStructure'>;
}
declare module 'picturebook/src/utils/folderStructure.spec.js' {
  declare module.exports: $Exports<'picturebook/src/utils/folderStructure.spec'>;
}
declare module 'picturebook/src/utils/getParents.js' {
  declare module.exports: $Exports<'picturebook/src/utils/getParents'>;
}
declare module 'picturebook/src/utils/image.js' {
  declare module.exports: $Exports<'picturebook/src/utils/image'>;
}
declare module 'picturebook/src/utils/index.js' {
  declare module.exports: $Exports<'picturebook/src/utils/index'>;
}
declare module 'picturebook/src/utils/logs.js' {
  declare module.exports: $Exports<'picturebook/src/utils/logs'>;
}
declare module 'picturebook/src/utils/moduleAsFunction.js' {
  declare module.exports: $Exports<'picturebook/src/utils/moduleAsFunction'>;
}
declare module 'picturebook/src/utils/moduleAsFunction.spec.js' {
  declare module.exports: $Exports<'picturebook/src/utils/moduleAsFunction.spec'>;
}
