// flow-typed signature: 7f876b264d0d63ba0abe9944c4c366cb
// flow-typed version: <<STUB>>/picturebook_v1.0.31/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'picturebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'picturebook' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'picturebook/actions' {
  declare module.exports: any
}

declare module 'picturebook/config/addons' {
  declare module.exports: any
}

declare module 'picturebook/config/config' {
  declare module.exports: any
}

declare module 'picturebook/config/postcss.config' {
  declare module.exports: any
}

declare module 'picturebook/config/webpack.config' {
  declare module.exports: any
}

declare module 'picturebook/knobs' {
  declare module.exports: any
}

declare module 'picturebook/params' {
  declare module.exports: any
}

declare module 'picturebook/screenshot' {
  declare module.exports: any
}

declare module 'picturebook/shared/babelrc' {
  declare module.exports: any
}

declare module 'picturebook/shared/getName' {
  declare module.exports: any
}

declare module 'picturebook/shared/index' {
  declare module.exports: any
}

declare module 'picturebook/shared/storyFolders/index' {
  declare module.exports: any
}

declare module 'picturebook/shared/storyFolders/shared' {
  declare module.exports: any
}

declare module 'picturebook/shared/storyFolders/test' {
  declare module.exports: any
}

declare module 'picturebook/shared/storyFolders/webpack' {
  declare module.exports: any
}

declare module 'picturebook/shared/withExtensions' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/assertions/compareScreenshot' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/commands/compareScreenshot' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/commands/seleniumEnd' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/nightwatch.conf' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/shared/index' {
  declare module.exports: any
}

declare module 'picturebook/test/screenshot/specs/index' {
  declare module.exports: any
}

// Filename aliases
declare module 'picturebook/actions.js' {
  declare module.exports: $Exports<'picturebook/actions'>
}
declare module 'picturebook/config/addons.js' {
  declare module.exports: $Exports<'picturebook/config/addons'>
}
declare module 'picturebook/config/config.js' {
  declare module.exports: $Exports<'picturebook/config/config'>
}
declare module 'picturebook/config/postcss.config.js' {
  declare module.exports: $Exports<'picturebook/config/postcss.config'>
}
declare module 'picturebook/config/webpack.config.js' {
  declare module.exports: $Exports<'picturebook/config/webpack.config'>
}
declare module 'picturebook/index' {
  declare module.exports: $Exports<'picturebook'>
}
declare module 'picturebook/index.js' {
  declare module.exports: $Exports<'picturebook'>
}
declare module 'picturebook/knobs.js' {
  declare module.exports: $Exports<'picturebook/knobs'>
}
declare module 'picturebook/params.js' {
  declare module.exports: $Exports<'picturebook/params'>
}
declare module 'picturebook/screenshot.js' {
  declare module.exports: $Exports<'picturebook/screenshot'>
}
declare module 'picturebook/shared/babelrc.js' {
  declare module.exports: $Exports<'picturebook/shared/babelrc'>
}
declare module 'picturebook/shared/getName.js' {
  declare module.exports: $Exports<'picturebook/shared/getName'>
}
declare module 'picturebook/shared/index.js' {
  declare module.exports: $Exports<'picturebook/shared/index'>
}
declare module 'picturebook/shared/storyFolders/index.js' {
  declare module.exports: $Exports<'picturebook/shared/storyFolders/index'>
}
declare module 'picturebook/shared/storyFolders/shared.js' {
  declare module.exports: $Exports<'picturebook/shared/storyFolders/shared'>
}
declare module 'picturebook/shared/storyFolders/test.js' {
  declare module.exports: $Exports<'picturebook/shared/storyFolders/test'>
}
declare module 'picturebook/shared/storyFolders/webpack.js' {
  declare module.exports: $Exports<'picturebook/shared/storyFolders/webpack'>
}
declare module 'picturebook/shared/withExtensions.js' {
  declare module.exports: $Exports<'picturebook/shared/withExtensions'>
}
declare module 'picturebook/test/screenshot/assertions/compareScreenshot.js' {
  declare module.exports: $Exports<
    'picturebook/test/screenshot/assertions/compareScreenshot'
  >
}
declare module 'picturebook/test/screenshot/commands/compareScreenshot.js' {
  declare module.exports: $Exports<
    'picturebook/test/screenshot/commands/compareScreenshot'
  >
}
declare module 'picturebook/test/screenshot/commands/seleniumEnd.js' {
  declare module.exports: $Exports<
    'picturebook/test/screenshot/commands/seleniumEnd'
  >
}
declare module 'picturebook/test/screenshot/nightwatch.conf.js' {
  declare module.exports: $Exports<
    'picturebook/test/screenshot/nightwatch.conf'
  >
}
declare module 'picturebook/test/screenshot/shared/index.js' {
  declare module.exports: $Exports<'picturebook/test/screenshot/shared/index'>
}
declare module 'picturebook/test/screenshot/specs/index.js' {
  declare module.exports: $Exports<'picturebook/test/screenshot/specs/index'>
}
