// flow-typed signature: ca685e54d5c46539bb5acb8fc7b890b0
// flow-typed version: <<STUB>>/postcss-nesting_v4.2.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nesting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nesting' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-nesting/lib/clean-node' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/get-closest-rule' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/merge-params' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/merge-selectors' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/transform-after-nodes' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/transform-bubbling-atrule' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/transform-nesting-atrule' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/transform-nesting-rule' {
  declare module.exports: any
}

declare module 'postcss-nesting/lib/transform' {
  declare module.exports: any
}

// Filename aliases
declare module 'postcss-nesting/index' {
  declare module.exports: $Exports<'postcss-nesting'>
}
declare module 'postcss-nesting/index.js' {
  declare module.exports: $Exports<'postcss-nesting'>
}
declare module 'postcss-nesting/lib/clean-node.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/clean-node'>
}
declare module 'postcss-nesting/lib/get-closest-rule.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/get-closest-rule'>
}
declare module 'postcss-nesting/lib/merge-params.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/merge-params'>
}
declare module 'postcss-nesting/lib/merge-selectors.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/merge-selectors'>
}
declare module 'postcss-nesting/lib/transform-after-nodes.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/transform-after-nodes'>
}
declare module 'postcss-nesting/lib/transform-bubbling-atrule.js' {
  declare module.exports: $Exports<
    'postcss-nesting/lib/transform-bubbling-atrule'
  >
}
declare module 'postcss-nesting/lib/transform-nesting-atrule.js' {
  declare module.exports: $Exports<
    'postcss-nesting/lib/transform-nesting-atrule'
  >
}
declare module 'postcss-nesting/lib/transform-nesting-rule.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/transform-nesting-rule'>
}
declare module 'postcss-nesting/lib/transform.js' {
  declare module.exports: $Exports<'postcss-nesting/lib/transform'>
}
