// flow-typed signature: 843d076bc3e2a5e4cb79e13c8abfeb1b
// flow-typed version: <<STUB>>/postcss-cli_v4.1.1/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-cli' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-cli/lib/args' {
  declare module.exports: any
}

declare module 'postcss-cli/lib/depGraph' {
  declare module.exports: any
}

// Filename aliases
declare module 'postcss-cli/index' {
  declare module.exports: $Exports<'postcss-cli'>
}
declare module 'postcss-cli/index.js' {
  declare module.exports: $Exports<'postcss-cli'>
}
declare module 'postcss-cli/lib/args.js' {
  declare module.exports: $Exports<'postcss-cli/lib/args'>
}
declare module 'postcss-cli/lib/depGraph.js' {
  declare module.exports: $Exports<'postcss-cli/lib/depGraph'>
}
