// flow-typed signature: dd5af7107ea27c0615350e242bfa60f6
// flow-typed version: <<STUB>>/preval.macro_v3.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preval.macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preval.macro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'preval.macro/index' {
  declare module.exports: $Exports<'preval.macro'>;
}
declare module 'preval.macro/index.js' {
  declare module.exports: $Exports<'preval.macro'>;
}
