// flow-typed signature: 727ff6f277a2aa7c7b6a6e05c7a1ed4f
// flow-typed version: <<STUB>>/regenerator-runtime_v0.11.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'regenerator-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'regenerator-runtime' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'regenerator-runtime/path' {
  declare module.exports: any
}

declare module 'regenerator-runtime/runtime-module' {
  declare module.exports: any
}

declare module 'regenerator-runtime/runtime' {
  declare module.exports: any
}

// Filename aliases
declare module 'regenerator-runtime/path.js' {
  declare module.exports: $Exports<'regenerator-runtime/path'>
}
declare module 'regenerator-runtime/runtime-module.js' {
  declare module.exports: $Exports<'regenerator-runtime/runtime-module'>
}
declare module 'regenerator-runtime/runtime.js' {
  declare module.exports: $Exports<'regenerator-runtime/runtime'>
}
