// flow-typed signature: fe1d7633d819a3444c19ecceee3cbd53
// flow-typed version: <<STUB>>/selenium-standalone_v6.15.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selenium-standalone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'selenium-standalone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selenium-standalone/lib/check-paths-existence' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/check-started' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/compute-download-urls' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/compute-fs-paths' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/debug-environment-details' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/default-config' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/get-selenium-status-url' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/install' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/microsoft-edge-releases' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/noop' {
  declare module.exports: any;
}

declare module 'selenium-standalone/lib/start' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/cli-parameters' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/compute-download-urls-test' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/default-downloads-test' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/fixtures/config.invalid' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/fixtures/config.valid' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/get-selenium-hub-test' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/no-files' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/no-reinstall' {
  declare module.exports: any;
}

declare module 'selenium-standalone/test/programmatic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selenium-standalone/index' {
  declare module.exports: $Exports<'selenium-standalone'>;
}
declare module 'selenium-standalone/index.js' {
  declare module.exports: $Exports<'selenium-standalone'>;
}
declare module 'selenium-standalone/lib/check-paths-existence.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/check-paths-existence'>;
}
declare module 'selenium-standalone/lib/check-started.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/check-started'>;
}
declare module 'selenium-standalone/lib/compute-download-urls.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/compute-download-urls'>;
}
declare module 'selenium-standalone/lib/compute-fs-paths.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/compute-fs-paths'>;
}
declare module 'selenium-standalone/lib/debug-environment-details.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/debug-environment-details'>;
}
declare module 'selenium-standalone/lib/default-config.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/default-config'>;
}
declare module 'selenium-standalone/lib/get-selenium-status-url.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/get-selenium-status-url'>;
}
declare module 'selenium-standalone/lib/install.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/install'>;
}
declare module 'selenium-standalone/lib/microsoft-edge-releases.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/microsoft-edge-releases'>;
}
declare module 'selenium-standalone/lib/noop.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/noop'>;
}
declare module 'selenium-standalone/lib/start.js' {
  declare module.exports: $Exports<'selenium-standalone/lib/start'>;
}
declare module 'selenium-standalone/test/cli-parameters.js' {
  declare module.exports: $Exports<'selenium-standalone/test/cli-parameters'>;
}
declare module 'selenium-standalone/test/compute-download-urls-test.js' {
  declare module.exports: $Exports<'selenium-standalone/test/compute-download-urls-test'>;
}
declare module 'selenium-standalone/test/default-downloads-test.js' {
  declare module.exports: $Exports<'selenium-standalone/test/default-downloads-test'>;
}
declare module 'selenium-standalone/test/fixtures/config.invalid.js' {
  declare module.exports: $Exports<'selenium-standalone/test/fixtures/config.invalid'>;
}
declare module 'selenium-standalone/test/fixtures/config.valid.js' {
  declare module.exports: $Exports<'selenium-standalone/test/fixtures/config.valid'>;
}
declare module 'selenium-standalone/test/get-selenium-hub-test.js' {
  declare module.exports: $Exports<'selenium-standalone/test/get-selenium-hub-test'>;
}
declare module 'selenium-standalone/test/no-files.js' {
  declare module.exports: $Exports<'selenium-standalone/test/no-files'>;
}
declare module 'selenium-standalone/test/no-reinstall.js' {
  declare module.exports: $Exports<'selenium-standalone/test/no-reinstall'>;
}
declare module 'selenium-standalone/test/programmatic.js' {
  declare module.exports: $Exports<'selenium-standalone/test/programmatic'>;
}
