// flow-typed signature: b727e7ab88b291c253ca384b49c3b0ea
// flow-typed version: <<STUB>>/semantic-release-cli_v3.2.6/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release-cli' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-release-cli/bin/semantic-release' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/index' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/ci' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/github' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/log' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/npm' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/password-storage' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/repository' {
  declare module.exports: any
}

declare module 'semantic-release-cli/src/lib/travis' {
  declare module.exports: any
}

// Filename aliases
declare module 'semantic-release-cli/bin/semantic-release.js' {
  declare module.exports: $Exports<'semantic-release-cli/bin/semantic-release'>
}
declare module 'semantic-release-cli/src/index.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/index'>
}
declare module 'semantic-release-cli/src/lib/ci.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/ci'>
}
declare module 'semantic-release-cli/src/lib/github.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/github'>
}
declare module 'semantic-release-cli/src/lib/log.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/log'>
}
declare module 'semantic-release-cli/src/lib/npm.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/npm'>
}
declare module 'semantic-release-cli/src/lib/password-storage.js' {
  declare module.exports: $Exports<
    'semantic-release-cli/src/lib/password-storage'
  >
}
declare module 'semantic-release-cli/src/lib/repository.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/repository'>
}
declare module 'semantic-release-cli/src/lib/travis.js' {
  declare module.exports: $Exports<'semantic-release-cli/src/lib/travis'>
}
