version: 2
jobs:
  build:
    working_directory: ~/gymnastjs/gymnast
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      TARGET_URL: https://gymnastjs.github.io/gymnast/branch/$CIRCLE_BRANCH
    docker:
      - image: circleci/openjdk:8-jdk-node
    steps:
      # Build, Test and Deploy
      - checkout
      - run: yarn
      # Test
      - run:
          name: 'Test'
          command: ./scripts/citests.sh
      # Deployment
      - type: deploy
        name: 'Publish to npm'
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo "Publishing latest release"
            ./scripts/deploynpm.sh
          elif [ "${CIRCLE_BRANCH}" == "next" ]; then
            echo "Publishing next release"
            ./scripts/deploynpm.sh
          else
            echo "Skipping publication in non-release branch"
          fi
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
