export { default as footer } from './footer.md'
export { default as getMarginSelect } from './margin'
export { default as getPositionSelect } from './position'
export { default as loremIpsum } from './loremIpsum'
export * from './box'
