// flow-typed signature: 0a46f9998dd705fce7a844e2b9909fb3
// flow-typed version: <<STUB>>/@bubltechnology/customizable-commit-analyzer_v1.0.2-0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bubltechnology/customizable-commit-analyzer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bubltechnology/customizable-commit-analyzer' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bubltechnology/customizable-commit-analyzer/lib/findMostRelevantUpdate' {
  declare module.exports: any
}

declare module '@bubltechnology/customizable-commit-analyzer/lib/typeMapFromPackage' {
  declare module.exports: any
}

declare module '@bubltechnology/customizable-commit-analyzer/tests/findMostRelevantUpdate-spec' {
  declare module.exports: any
}

declare module '@bubltechnology/customizable-commit-analyzer/tests/typeMapFromPackage-spec' {
  declare module.exports: any
}

// Filename aliases
declare module '@bubltechnology/customizable-commit-analyzer/index' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer'
  >
}
declare module '@bubltechnology/customizable-commit-analyzer/index.js' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer'
  >
}
declare module '@bubltechnology/customizable-commit-analyzer/lib/findMostRelevantUpdate.js' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer/lib/findMostRelevantUpdate'
  >
}
declare module '@bubltechnology/customizable-commit-analyzer/lib/typeMapFromPackage.js' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer/lib/typeMapFromPackage'
  >
}
declare module '@bubltechnology/customizable-commit-analyzer/tests/findMostRelevantUpdate-spec.js' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer/tests/findMostRelevantUpdate-spec'
  >
}
declare module '@bubltechnology/customizable-commit-analyzer/tests/typeMapFromPackage-spec.js' {
  declare module.exports: $Exports<
    '@bubltechnology/customizable-commit-analyzer/tests/typeMapFromPackage-spec'
  >
}
